"""Add enhanced sets

Revision ID: 6231939ce8d3
Revises: a33d17afabd5
Create Date: 2025-05-01 22:20:28.253814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6231939ce8d3'
down_revision: Union[str, None] = 'a33d17afabd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('day', sa.String(), nullable=True))
    op.add_column('workout_sets', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('workout_sets', 'duration')
    op.drop_column('workout_sets', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('notes', sa.VARCHAR(), nullable=True))
    op.add_column('workout_sets', sa.Column('duration', sa.INTEGER(), nullable=True))
    op.drop_column('workout_sets', 'type')
    op.drop_column('workout_sets', 'day')
    # ### end Alembic commands ###
