"""Add enhanced workout tracking fields

Revision ID: 8310b70397b0
Revises: dd236a77ca0f
Create Date: 2025-05-01 21:19:33.821414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8310b70397b0'
down_revision: Union[str, None] = 'dd236a77ca0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('workouts', 'workout_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_date', sa.DATE(), nullable=True))
    op.drop_column('workouts', 'date')
    op.drop_column('workouts', 'notes')
    op.drop_column('workouts', 'duration')
    op.drop_column('workouts', 'weight')
    # ### end Alembic commands ###
