"""Add enhanced workout

Revision ID: a33d17afabd5
Revises: 8310b70397b0
Create Date: 2025-05-01 22:10:39.208778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33d17afabd5'
down_revision: Union[str, None] = '8310b70397b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workouts_id', table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise', sa.VARCHAR(), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workouts_id', 'workouts', ['id'], unique=False)
    # ### end Alembic commands ###
