"""rename date field

Revision ID: dd236a77ca0f
Revises: d3d21faed381
Create Date: 2025-05-01 17:44:04.663181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd236a77ca0f'
down_revision: Union[str, None] = 'd3d21faed381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_date', sa.Date(), nullable=True))
    op.drop_column('workouts', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('workouts', 'workout_date')
    # ### end Alembic commands ###
